---
title: "Primaquine challenge studies"
format: html
editor: visual
---

```{r preambule}
#| echo: false
knitr::opts_chunk$set(cache = F, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)
library(RColorBrewer)
```

## Load all data

```{r load_data}
Ascending_dat = read.csv('PQAscending.csv')
PQ45_dat = read.csv('PQ45.csv')
```

## Endpoints definitions

```{r endpoints}
# Maximum fall (absolute)
xx_max_abs = aggregate((Baseline_Hb-Mean_Hb) ~ label, 
                       data = Ascending_dat,FUN = max)
colnames(xx_max_abs)[2]='Max_Hb_decrease_Abs'

# Maximum fall (relative to baseline Hb)
xx_max_rel = aggregate(100*(Baseline_Hb-Mean_Hb)/Baseline_Hb ~ label, 
                       data = Ascending_dat,FUN = max)
colnames(xx_max_rel)[2]='Max_Hb_decrease_Rel'

xx_hb_falls = merge(xx_max_abs, xx_max_rel,by='label')

# Volunteer 18 was excluded
xx_hb_falls = xx_hb_falls[!xx_hb_falls$label=='PQ-mrdt01-018',]

xx_hb_falls$Daily_5_to_10 = NA
for(id in unique(xx_hb_falls$label)){
  i = which(xx_hb_falls$label==id)
  ind = !is.na(Ascending_dat$Mean_Hb) & 
    Ascending_dat$label==id & 
    Ascending_dat$visit>5 &
    Ascending_dat$visit<=10
  xx_hb_falls$Daily_5_to_10[i]= -coef(lm(Mean_Hb ~ visit, data = Ascending_dat[ind, ]))['visit']
}
Ascending_dat = merge(Ascending_dat, xx_hb_falls, by='label', all = T)
Ascending_dat = dplyr::arrange(Ascending_dat, label, visit)

Ascending_dat$nadir=NA
Ascending_dat$Peak_Retics=NA
for(id in unique(xx_hb_falls$label)){
  ind = Ascending_dat$label==id
  j=which.min(Ascending_dat$Mean_Hb[ind])
  Ascending_dat$nadir[ind] = Ascending_dat$visit[ind][j]
  j=which.max(Ascending_dat$Mean_Retic[ind])
  Ascending_dat$Peak_Retics[ind] = Ascending_dat$visit[ind][j]

}
writeLines('Absolute falls in ascending dose regimens:')
quantile(xx_hb_falls$Max_Hb_decrease_Abs, probs = c(0,.5,1))
writeLines('Relative falls in ascending dose regimens:')
quantile(xx_hb_falls$Max_Hb_decrease_Rel, probs = c(0,.5,1))
```


single dose

```{r}
# Maximum fall (absolute)
xx_max_abs = aggregate((Baseline_Hb-Mean_Hb) ~ label, 
                       data = PQ45_dat,FUN = max)
colnames(xx_max_abs)[2]='Max_Hb_decrease_Abs'

# Maximum fall (relative to baseline Hb)
xx_max_rel = aggregate(100*(Baseline_Hb-Mean_Hb)/Baseline_Hb ~ label, 
                       data = PQ45_dat,FUN = max)
colnames(xx_max_rel)[2]='Max_Hb_decrease_Rel'

xx_hb_falls = merge(xx_max_abs, xx_max_rel,by='label')

xx_hb_falls$Daily_0_to_7 = NA
for(id in unique(xx_hb_falls$label)){
  i = which(xx_hb_falls$label==id)
  ind = !is.na(PQ45_dat$Mean_Hb) & 
    PQ45_dat$label==id & 
    PQ45_dat$visit>=0 &
    PQ45_dat$visit<=7
  xx_hb_falls$Daily_0_to_7[i]= -coef(lm(Mean_Hb ~ visit, data = PQ45_dat[ind, ]))['visit']
}
PQ45_dat = merge(PQ45_dat, xx_hb_falls, by='label', all = T)
PQ45_dat = dplyr::arrange(PQ45_dat, label, visit)


writeLines('Absolute falls in single dose:')
quantile(xx_hb_falls$Max_Hb_decrease_Abs, probs = c(0,.5,1))
writeLines('Relative falls in single dose:')
quantile(xx_hb_falls$Max_Hb_decrease_Rel, probs = c(0,.5,1))
```

## Exposure definitions

```{r}
# color ramp for plots
my_pal = colorRampPalette(colors = rev(brewer.pal(n = 9,name = 'RdYlBu')))

Ascending_dat$day10_PQ_cum = NA
Ascending_dat$total_PQ = NA

for(id in unique(Ascending_dat$label)){
  ind=Ascending_dat$label==id
  Ascending_dat$day10_PQ_cum[ind]=
    Ascending_dat$PQ_mg_kg_cum[Ascending_dat$visit==10 & ind]
  Ascending_dat$total_PQ[ind] = max(Ascending_dat$PQ_mg_kg_cum[ind])
}
# make colors by day 10 total PQ mg/kg
ind_include = Ascending_dat$day10_PQ_cum>1
Ascending_dat$col = 'grey'
Ascending_dat$col[ind_include] = my_pal(17)[round(Ascending_dat$day10_PQ_cum[ind_include],1)*10-13]

PQ45_dat$col = my_pal(36)[round(PQ45_dat$PQ_mg_kg,2)*100-51]

```

## Table 1

Part 1 - ascending dose

```{r part1_table}
Ascending_base_dat = Ascending_dat[!duplicated(Ascending_dat$label),]
writeLines('G6PD variants:')
table(Ascending_base_dat$G6PD_variant)
writeLines('G6PD enzyme activity:')
quantile(Ascending_base_dat$Baseline_G6PD, probs = c(0, .5, 1))
writeLines('Age (years):')
quantile(Ascending_base_dat$agey, probs = c(0, .5, 1))
writeLines('Weight (kg):')
quantile(Ascending_base_dat$weight, probs = c(0, .5, 1))
writeLines('Baseline Hb:')
round(quantile(Ascending_base_dat$Baseline_Hb, probs = c(0, .5, 1)),1)
writeLines('Baseline retics:')
round(quantile(Ascending_base_dat$Baseline_Retic, probs = c(0, .5, 1)),1)

sort(table(Ascending_dat$label[Ascending_dat$sddose>0]))

writeLines('Day of nadir:')
quantile(Ascending_base_dat$nadir, probs = c(0, .5, 1),na.rm = T)
writeLines('Day of peak retics:')
quantile(Ascending_base_dat$Peak_Retics, probs = c(0, .5, 1),na.rm = T)
```


```{r part2_table}
PQ45_base = PQ45_dat[!duplicated(PQ45_dat$label), ]

writeLines('G6PD variants:')
table(PQ45_base$G6PD_variant)
writeLines('G6PD enzyme activity:')
# quantile(PQ45_dat$, probs = c(0, .5, 1))
writeLines('Age (years):')
quantile(PQ45_base$Age, probs = c(0, .5, 1))
writeLines('Weight (kg):')
quantile(PQ45_base$weight, probs = c(0, .5, 1))
writeLines('Baseline Hb:')
round(quantile(PQ45_base$Baseline_Hb, probs = c(0, .5, 1)),1)
writeLines('Baseline retics:')
round(quantile(PQ45_base$Baseline_Retic, probs = c(0, .5, 1)),1)
```

## Part 1

```{r Fig1}
par(las=1, mfrow=c(2,2), family='serif', cex.lab=1.3, cex.axis=1.3)
plot(NA, NA, panel.first=grid(), 
     xlab='Days since start of primaquine',
     ylab ='Total PQ dose (mg/kg)',xlim=c(0,28),
     ylim = c(0, max(Ascending_dat$PQ_mg_kg_cum)))
for(id in unique(Ascending_dat$label)){
  ind = Ascending_dat$label==id 
  lines(Ascending_dat$visit[ind], Ascending_dat$PQ_mg_kg_cum[ind],
        col = Ascending_dat$col[ind],lwd=1.5)
}
abline(v=10, lty=2, lwd=2, col='grey')
mtext(text = 'a',side = 3,line = 2,cex = 1.5,adj = 0)

plot(Ascending_dat$visit, 
     Ascending_dat$Mean_Hb, pch ='.',xlim=c(0,28),
     xlab='Days since start of primaquine',
     ylab = 'Haemoglobin (g/dL)', panel.first =grid())
for(id in unique(Ascending_dat$label)){
  ind = Ascending_dat$label==id & !is.na(Ascending_dat$Mean_Hb)
  lines(Ascending_dat$visit[ind], Ascending_dat$Mean_Hb[ind],
        col = Ascending_dat$col[ind],lwd=1.5)
}
mtext(text = 'b',side = 3,line = 2,cex = 1.5,adj = 0)

plot(Ascending_dat$visit,
     Ascending_dat$Mean_Retic, xlim=c(0,28),
     pch ='.', xlab='Days since start of primaquine',
     ylab = 'Reticulocytes (%)', panel.first =grid())
for(id in unique(Ascending_dat$label)){
  ind = Ascending_dat$label==id & !is.na(Ascending_dat$Mean_Retic)
  lines(Ascending_dat$visit[ind], Ascending_dat$Mean_Retic[ind],
        col = Ascending_dat$col[ind],lwd=1.5)
}
mtext(text = 'c',side = 3,line = 2,cex = 1.5,adj = 0)


plot(Ascending_dat$visit,
     100*Ascending_dat$Mean_Hb/Ascending_dat$Baseline_Hb, 
     xlim=c(0,28),
     pch ='.', xlab='Days since start of primaquine',
     ylab = 'Baseline haemoglobin (%)', panel.first =grid())
for(id in unique(Ascending_dat$label)){
  ind = Ascending_dat$label==id & !is.na(Ascending_dat$Mean_Hb)
  lines(Ascending_dat$visit[ind],
        100*Ascending_dat$Mean_Hb[ind]/Ascending_dat$Baseline_Hb[ind],
        col = Ascending_dat$col[ind],lwd=1.5)
}
mtext(text = 'd',side = 3,line = 2,cex = 1.5,adj = 0)
```

## Part 2

```{r Fig2, fig.height=6, fig.width=8}
par(las=1, mfrow=c(1,2), family='serif', cex.lab=1.3, cex.axis=1.3)

plot(PQ45_dat$visit,PQ45_dat$Mean_Hb, pch ='.',
     xlab='Days since primaquine dose (45 mg)',xaxt='n',xlim=c(0,14),
     ylab = 'Haemoglobin (g/dL)', panel.first =grid())
axis(1, at = c(0,3,7,14))
for(id in unique(PQ45_dat$label)){
  ind = PQ45_dat$label==id & !is.na(PQ45_dat$Mean_Hb)
  lines(PQ45_dat$visit[ind], PQ45_dat$Mean_Hb[ind], col = PQ45_dat$col[ind],lwd=1.5)
}
mtext(text = 'a',side = 3,line = 2,cex = 1.5,adj = 0)

plot(PQ45_dat$visit,
     PQ45_dat$Mean_Retic, xlim=c(0,14),
     col = PQ45_dat$col[ind],
     pch ='.', xlab='Days since primaquine dose (45 mg)',
     ylab = 'Reticulocytes (%)', panel.first =grid())
for(id in unique(PQ45_dat$label)){
  ind = PQ45_dat$label==id & !is.na(PQ45_dat$Mean_Retic)
  lines(PQ45_dat$visit[ind], PQ45_dat$Mean_Retic[ind],
        col =  PQ45_dat$col[ind],lwd=1.5)
}
mtext(text = 'b',side = 3,line = 2,cex = 1.5,adj = 0)
ind_show = c(0.52,0.60,0.70,0.80,0.87)
legend('topleft',inset = 0.02,title = 'mg/kg dose',
       legend = ind_show,
       col = my_pal(36)[100*ind_show-51],lwd=2)
```

## Dose response part 1

```{r Fig3}
Ascending_base_dat$G6PD_variant_pch = as.numeric(as.factor(Ascending_base_dat$G6PD_variant))
g6pd_cols = brewer.pal(8,name = 'Set2')
names(g6pd_cols) = union(Ascending_base_dat$G6PD_variant, PQ45_dat$G6PD_variant)

writeLines('Total day 10 dose (mg/kg)')

ind = !is.na(Ascending_base_dat$Max_Hb_decrease_Abs)
round(quantile(Ascending_base_dat$day10_PQ_cum[ind], probs=c(0,.5,1)),1)

round(quantile(Ascending_base_dat$Max_Hb_decrease_Abs[ind], probs=c(0,.5,1)),1)

round(quantile(Ascending_base_dat$Max_Hb_decrease_Rel[ind], probs=c(0,.5,1)),1)

par(mfrow=c(2,2),las=1, family='serif', cex.lab=1.3, cex.axis=1.3)
plot(Ascending_base_dat$day10_PQ_cum, Ascending_base_dat$Max_Hb_decrease_Abs,
     xlim = c(1.4, 3), xlab = "Cumulative PQ dose by day 10 (mg/kg)",
     ylab = 'Maximum fall from baseline (g/dL)', panel.first = grid(),
     pch = Ascending_base_dat$G6PD_variant_pch, cex=1.5,
     col = g6pd_cols[Ascending_base_dat$G6PD_variant] )
mod=lm(Max_Hb_decrease_Abs~day10_PQ_cum,data = Ascending_base_dat)
summary(mod)
abline(mod,lty=2,lwd=2)

plot(Ascending_base_dat$day10_PQ_cum, Ascending_base_dat$Max_Hb_decrease_Rel,
     xlim = c(1.4, 3), xlab = "Cumulative PQ dose by day 10 (mg/kg)",
     ylab = 'Relative fall from baseline (%)', panel.first = grid(),
     pch = Ascending_base_dat$G6PD_variant_pch, cex=1.5,
     col = g6pd_cols[Ascending_base_dat$G6PD_variant] )
mod=lm(Max_Hb_decrease_Rel~day10_PQ_cum,data = Ascending_base_dat)
summary(mod)
abline(mod,lty=2,lwd=2)


plot(Ascending_base_dat$day10_PQ_cum, Ascending_base_dat$Daily_5_to_10,
     xlim = c(1.4, 3), xlab = "Cumulative PQ dose by day 10 (mg/kg)",
     ylab = 'Mean fall: days 5-10 (g/dL) ', panel.first = grid(),
     pch = Ascending_base_dat$G6PD_variant_pch, cex=1.5,
     col = g6pd_cols[Ascending_base_dat$G6PD_variant] )
mod=lm(Daily_5_to_10~day10_PQ_cum,data = Ascending_base_dat)
summary(mod)
abline(mod,lty=2,lwd=2)

plot(NA, NA, xlim=0:1, ylim=0:1, xlab='',ylab='',bty='n',xaxt='n',yaxt='n')
legend('topleft', inset = 0.03, legend = unique(Ascending_base_dat$G6PD_variant),
       col = g6pd_cols[unique(Ascending_base_dat$G6PD_variant)],
       bty='n',pch=unique(Ascending_base_dat$G6PD_variant_pch),cex=1.5)

```

## Dose response part 2

single dose 

```{r fig4}
par(mfrow=c(2,2),las=1, family='serif', cex.lab=1.3, cex.axis=1.3)
plot(PQ45_base$PQ_mg_kg, PQ45_base$Max_Hb_decrease_Abs,
      xlab = "PQ single dose (mg/kg)",
     ylab = 'Maximum fall from baseline (g/dL)', panel.first = grid(),
     pch = 16, cex=1.5,
     col = g6pd_cols[PQ45_base$G6PD_variant] )
mod=lm(Max_Hb_decrease_Abs~PQ_mg_kg,data = PQ45_base)
summary(mod)
abline(mod,lty=2,lwd=2)

plot(PQ45_base$PQ_mg_kg, PQ45_base$Max_Hb_decrease_Rel,
     xlab = "PQ single dose (mg/kg)",
     ylab = 'Relative fall from baseline (%)', panel.first = grid(),
     pch = 16, cex=1.5,
     col = g6pd_cols[PQ45_base$G6PD_variant] )
mod=lm(Max_Hb_decrease_Rel~PQ_mg_kg,data = PQ45_base)
summary(mod)
abline(mod,lty=2,lwd=2)


plot(PQ45_base$PQ_mg_kg, PQ45_base$Daily_0_to_7,
     xlab = "PQ single dose (mg/kg)",
     ylab = 'Mean fall: days 0-7 (g/dL) ', panel.first = grid(),
     pch = 16, cex=1.5,
     col = g6pd_cols[PQ45_base$G6PD_variant] )
mod=lm(Daily_0_to_7~PQ_mg_kg,data = PQ45_base)
summary(mod)
abline(mod,lty=2,lwd=2)

plot(NA, NA, xlim=0:1, ylim=0:1, xlab='',ylab='',bty='n',xaxt='n',yaxt='n')
legend('topleft', inset = 0.03, legend = unique(PQ45_base$G6PD_variant),
       col = g6pd_cols[unique(PQ45_base$G6PD_variant)],
       bty='n',pch=16,cex=1.5)
```

```{r comparison_endpoints, fig.height=6, fig.width=8}
par(mfrow=c(1,2),las=1)
plot(Ascending_base_dat$total_PQ, Ascending_base_dat$Max_Hb_decrease_Abs,
     ylim =c(0,6),panel.first=grid(),pch=16,xlim=c(0,8.5),
     ylab='Maximum fall in haemoglobin (g/dL)',
     xlab = "Total PQ dose (mg/kg)",col='darkblue')
abline(h=median(Ascending_base_dat$Max_Hb_decrease_Abs,na.rm=T),
       lty=2,col='darkblue',lwd=2)
points(PQ45_base$PQ_mg_kg, PQ45_base$Max_Hb_decrease_Abs,col='pink',pch=15)
abline(h=median(PQ45_base$Max_Hb_decrease_Abs),lty=2,col='pink',lwd=2)
text(x=1,y=0.5,'Single\ndose',col='pink')
text(x=5,y=0.5,'Ascending\ndose',col='darkblue')

plot(Ascending_base_dat$total_PQ, Ascending_base_dat$Max_Hb_decrease_Rel,
     xlim =c(0,8.5),panel.first=grid(),pch=16,ylim=c(0,40),
     ylab='Maximum relative fall in haemoglobin (%)',
     xlab = "Total PQ dose (mg/kg)",col='darkblue')
abline(h=median(Ascending_base_dat$Max_Hb_decrease_Rel,na.rm=T),
       lty=2,col='darkblue',lwd=2)
points(PQ45_base$PQ_mg_kg, PQ45_base$Max_Hb_decrease_Rel,col='pink',pch=15)
abline(h=median(PQ45_base$Max_Hb_decrease_Rel),lty=2,col='pink',lwd=2)
text(x=1,y=4,'Single\ndose',col='pink')
text(x=5,y=4,'Ascending\ndose',col='darkblue')
```



## Individual data

```{r individ_profiles_ascending}
par(mfcol=c(4,4),las=1, family='serif', mar = c(0,5,2,2),cex.lab=1.3,cex.axis=1.3)
Ascending_dat$ID = as.numeric(as.factor(Ascending_dat$label))
for(id in unique(Ascending_dat$ID)){
  par(mar = c(0,5,4,2))
  ind = Ascending_dat$ID==id
  
  # retics
  plot(Ascending_dat$visit[ind],
       Ascending_dat$Manual_retic[ind],
       panel.first = grid(),xlim=c(0,28),
       ylim = c(0,18), col='darkblue',
       main = paste0(id, ' (',Ascending_dat$G6PD_variant[ind][1],')'),
       pch=16, ylab='Reticulocyte (%)',
       xlab = '', xaxt='n')
  points(Ascending_dat$visit[ind],
         Ascending_dat$CBC_retic[ind], pch=17,col='darkred')
  par(mar = c(4,5,0,2))
  
  plot(Ascending_dat$visit[ind],
       Ascending_dat$Haemocue_hb[ind],
       panel.first = grid(),col='darkblue',xlim=c(0,28),
       ylim = range(union(Ascending_dat$Haemocue_hb,
                          Ascending_dat$CBC_hb),na.rm = T),
       main = '',pch=16, ylab='Haemoglobin (g/dL)',
       xlab = '')
  mtext(text = 'Days since starting PQ',side = 1,line = 3,cex=.8)
  points(Ascending_dat$visit[ind],
         Ascending_dat$CBC_hb[ind], pch=17,col='darkred')
}
```


```{r individ_profiles_PQ45}
par(mfcol=c(4,4),las=1, family='serif', mar = c(0,5,2,2),cex.lab=1.3,cex.axis=1.3)

for(id in unique(PQ45_dat$label)){
  par(mar = c(0,5,4,2))
  ind = PQ45_dat$label==id
  not_na_retic = !is.na(PQ45_dat$Mean_Retic)
  
  # retics
  plot(PQ45_dat$visit[ind&not_na_retic],
       PQ45_dat$Mean_Retic[ind&not_na_retic],
       xlim=range(PQ45_dat$visit,na.rm = T),
       panel.first = grid(),type='b',
       ylim = c(0,9), col='darkred',
       main = paste0(id, ' (',PQ45_dat$G6PD_variant[ind][1],')'),
       pch=17, ylab='Reticulocyte (%)',
       xlab = '', xaxt='n')
  par(mar = c(4,5,0,2))
  
  not_na_hb = !is.na(PQ45_dat$Haemocue_hb)
  plot(PQ45_dat$visit[ind&not_na_hb],
       PQ45_dat$Haemocue_hb[ind&not_na_hb],
       xlim=range(PQ45_dat$visit,na.rm = T),
       panel.first = grid(),col='darkblue',type='b',
       ylim = range(union(PQ45_dat$Haemocue_hb,
                          PQ45_dat$CBC_hb),na.rm = T),
       main = '',pch=16, ylab='Haemoglobin (g/dL)',
       xlab = '')
  mtext(text = 'Days since PQ',side = 1,line = 3,cex=.8)
  not_na_hb = !is.na(PQ45_dat$CBC_hb)
  lines(PQ45_dat$visit[ind&not_na_hb],PQ45_dat$CBC_hb[ind&not_na_hb],
        type='b', pch=17,col='darkred')
}
```

patients who got both

```{r comparison_both_parts}
ids_both = sort(unique(PQ45_dat$Ascending_ID[!is.na(PQ45_dat$Ascending_ID)]))
all(ids_both %in% Ascending_base_dat$label)

par(las=1, family='serif')
layout(mat = matrix(c(1,2,2,3,4,4,
                      5,6,6,7,8,8),
                      # 9,10,10,11,12,12,
                      # 13,14,14,15,16,16),
                    nrow = 6,byrow = F))
for(id in ids_both){
  par(mar=c(0,5,4,2))
  ind_dose = Ascending_dat$label==id
  plot(Ascending_dat$visit[ind_dose],
       Ascending_dat$PQ_cumulative[ind_dose],type='l',lwd=2,
       ylab='',xlab = '',xaxt='n', panel.first=grid(), xlim=c(0,20),
       ylim = range(Ascending_dat$PQ_cumulative), col='darkblue')
  abline(h=45, lty=2,lwd=2, col='pink')
  ind = Ascending_dat$label==id
  ind2 = PQ45_dat$Ascending_ID==id
    title(paste0(id, ' (',Ascending_dat$G6PD_variant[ind][1],')'))

  par(mar=c(5,5,0,2))
  plot(Ascending_dat$visit[ind], Ascending_dat$Mean_Hb[ind],
       xlim = c(0,20), panel.first=grid(),type='b',ylim = c(8.5, 16),lwd=2,
       xlab='Days since starting PQ', ylab='Haemoglobin (g/dL)',col='darkblue')
  lines(PQ45_dat$visit[ind2], PQ45_dat$Mean_Hb[ind2], type='b',col='pink',lwd=2)
}
```


drop in haemoglobin once PQ was stopped

```{r}
Ascending_dat = dplyr::arrange(Ascending_dat, label, visit)
Ascending_dat$final_dose = NA
Ascending_dat$post_regimen_drop = NA
for(id in unique(Ascending_dat$label)){
  ind = Ascending_dat$label==id
  j_last = tail(which(ind & Ascending_dat$sddose>0), 1)
  Ascending_dat$final_dose[ind] = Ascending_dat$sddose[j_last]
  
  fup_ind = which(ind & Ascending_dat$visit>0 & Ascending_dat$sddose==0 & !is.na(Ascending_dat$Mean_Hb))
  Ascending_dat$post_regimen_drop[ind] = max(Ascending_dat$Mean_Hb[j_last]-Ascending_dat$Mean_Hb[fup_ind])
}
Ascending_base_dat = Ascending_dat[!duplicated(Ascending_dat$label),]

par(las=1, family='serif', cex.lab=1.3, cex.axis=1.3)
plot(Ascending_base_dat$final_dose/Ascending_base_dat$weight,
     Ascending_base_dat$post_regimen_drop,
     xlab='Final dose given (mg)',ylab='Maximum fall post final dose',
     panel.first=grid())
```


