---
title: "RBC model results"
format: html
editor: visual
---


```{r preambule}
#| echo: false
knitr::opts_chunk$set(cache = F, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)
library(RColorBrewer)
library(gtools)
library(rstan)
source('master_functions.R')
load('Rout/pop_fit1.RData')
Y_hat1 = rstan::extract(mod_fit_pop1, pars='Y_hat')$Y_hat
pars = c("Hb_steady_state", "rbc_lifespan_steady_state",
         "alpha_diff1", "alpha_delta1", "alpha_diff2", "alpha_delta2",
         "logit_max_drug_effect",
         "ed50", "emax_k",'mean_delay','logit_max_drug_effect',
         'theta_rand')
my_thetas1 = rstan::extract(mod_fit_pop1, pars=pars)
```

## Model checks

```{r traceplot}
#| echo: false
traceplot(mod_fit_pop1, 
          pars=c("Hb_steady_state", "rbc_lifespan_steady_state",
                 "alpha_diff1", "alpha_delta1", "alpha_diff2",
                 "alpha_delta2",
                 "logit_max_drug_effect",
                 "ed50", "emax_k",'mean_delay',
                 'sigma_delay','logit_max_drug_effect',
                 'sigma_CBC', 'sigma_manual'))
```

## Individual fits


```{r individual_fits_hb}
#| echo: false
par(mfrow=c(4,4),las=1,family='serif',cex.lab=1.3, cex.axis=1.3,mar=c(2,2,2,2))
for(id in 1:stan_data$N){
  ind_id = stan_data$ind_start_regimen[id]:stan_data$ind_end_regimen[id]
  Y_hat_hb = Y_hat1[,1,ind_id]

  ind_haemocue = stan_data$t_sim_hemocue_Hb[stan_data$ind_start_Hb_hemocue[id]:stan_data$ind_end_Hb_hemocue[id]]
  ind_hb_CBC = stan_data$t_sim_CBC_Hb[stan_data$ind_start_Hb_CBC[id]:stan_data$ind_end_Hb_CBC[id]]
  
  plot(1:length(ind_id), colMeans(Y_hat_hb), type='l', lwd=2,
       panel.first=grid(), ylim =c(8.3,16.3), xlab='',
       ylab='',main=ID_map$ID_combined[id],col='grey')
  dosing_ind = which(stan_data$drug_regimen[ind_id]>0)
  dosing_ind = c(head(dosing_ind,1), tail(dosing_ind,1)+1)
  polygon(c(dosing_ind, rev(dosing_ind)), c(0,0,20,20),col=adjustcolor('pink',.3),border = NA)
  
  polygon(c(1:length(ind_id), rev(1:length(ind_id))),
          c(apply(Y_hat_hb,2, quantile,probs=0.1), rev(apply(Y_hat_hb,2,quantile,probs=0.9))),
          col=adjustcolor('grey',.3),border = NA)
  lines(1:length(ind_id), colMeans(Y_hat_hb), lwd=2, col='grey')
  
  points((1:length(ind_id))[ind_haemocue],
         stan_data$Hb_Haemocue[stan_data$ind_start_Hb_hemocue[id]:stan_data$ind_end_Hb_hemocue[id]], 
         pch =16,cex=1)
  points((1:length(ind_id))[ind_hb_CBC],
         stan_data$Hb_CBC[stan_data$ind_start_Hb_CBC[id]:stan_data$ind_end_Hb_CBC[id]], 
         pch =16, col='blue',cex=1)

}

```



```{r individual_fits_retic}
#| echo: false
par(mfrow=c(4,4),las=1,family='serif',cex.lab=1.3, cex.axis=1.3,mar=c(2,2,2,2))
for(id in 1:stan_data$N){
  ind_id = stan_data$ind_start_regimen[id]:stan_data$ind_end_regimen[id]
  Y_hat_retic = Y_hat1[,2,ind_id]

   ind_retic = stan_data$t_sim_retic[stan_data$ind_start_retic[id]:stan_data$ind_end_retic[id]]
  
  plot(1:length(ind_id), colMeans(Y_hat_retic), type='l', lwd=2,
       panel.first=grid(), ylim =c(0,20), xlab='',
       ylab='',main=ID_map$ID_combined[id],col='grey')
  dosing_ind = which(stan_data$drug_regimen[ind_id]>0)
  dosing_ind = c(head(dosing_ind,1), tail(dosing_ind,1)+1)
  polygon(c(dosing_ind, rev(dosing_ind)), c(0,0,20,20),col=adjustcolor('pink',.3),border = NA)
  
  polygon(c(1:length(ind_id), rev(1:length(ind_id))),
          c(apply(Y_hat_retic,2, quantile,probs=0.1), rev(apply(Y_hat_retic,2,quantile,probs=0.9))),
          col=adjustcolor('grey',.3),border = NA)
  lines(1:length(ind_id), colMeans(Y_hat_retic), lwd=2, col='grey')
  
  points((1:length(ind_id))[ind_retic],
         stan_data$Retic_data[stan_data$ind_start_retic[id]:stan_data$ind_end_retic[id]], 
         pch =16,cex=1)
}

```



## Dose-response curve

```{r dose_response}
#| echo: false
par(las=1, family='serif', cex.lab=1.3, cex.axis=1.3)
xs = seq(0,1,length.out=200)
effect = array(dim=c(length(my_thetas1$ed50), length(xs)))
for(i in 1:length(xs)){
  effect[,i] = emax_f(x = xs[i], 
                      logit_max_drug_effect = my_thetas1$logit_max_drug_effect,
                      emax_k = my_thetas1$emax_k, 
                      ed50 = my_thetas1$ed50)
}
effect_mean = colMeans(effect)
plot(xs, 100*effect_mean,type='l',lwd=3, xlab='Primaquine mg/kg',
     ylab='Reduction in red cell lifespan (%)',panel.first=grid(),
     ylim = c(0,60))
polygon(c(xs, rev(xs)),
        100*c(apply(effect,2, quantile,probs=0.1), rev(apply(effect,2,quantile,probs=0.9))),
        col=adjustcolor('grey',.3),border = NA)


effect_id_list = effect_id_list2 = list()
for(id in 1:stan_data$N){
  logit_max_drug_effect = my_thetas1$logit_max_drug_effect+my_thetas1$theta_rand[,id,6]
  emax_k = my_thetas1$emax_k*exp(my_thetas1$theta_rand[,id,7])
  ed50 = my_thetas1$ed50*exp(my_thetas1$theta_rand[,id,8])
  
 
  effect_id = array(dim=c(length(my_thetas1$ed50), length(xs)))
  for(i in 1:length(xs)){
    effect_id[,i]= emax_f(x = xs[i], 
                          logit_max_drug_effect = logit_max_drug_effect,
                          emax_k = emax_k, ed50 = ed50)
  }
  effect_id_list[[id]]=colMeans(effect_id)

  lines(xs, 100*colMeans(effect_id), col='lightgrey')
}
lines(xs, 100*colMeans(effect),lwd=3,col='red')

```

```{r dose_response_variant}
all_vars
#| echo: false
par(las=1, family='serif', cex.lab=1.3, cex.axis=1.3)
xs = seq(0,1,length.out=200)
effect = array(dim=c(length(my_thetas1$ed50), length(xs)))
for(i in 1:length(xs)){
  effect[,i] = emax_f(x = xs[i], 
                      logit_max_drug_effect = my_thetas1$logit_max_drug_effect,
                      emax_k = my_thetas1$emax_k, 
                      ed50 = my_thetas1$ed50)
}
effect_mean = colMeans(effect)
plot(xs, 100*effect_mean,type='l',lwd=3, xlab='Primaquine mg/kg',
     ylab='Reduction in red cell lifespan (%)',panel.first=grid(),
     ylim = c(0,60))
polygon(c(xs, rev(xs)),
        100*c(apply(effect,2, quantile,probs=0.1), rev(apply(effect,2,quantile,probs=0.9))),
        col=adjustcolor('grey',.3),border = NA)


effect_id_list = effect_id_list2 = list()
for(id in 1:stan_data$N){
  logit_max_drug_effect = my_thetas1$logit_max_drug_effect+my_thetas1$theta_rand[,id,6]
  emax_k = my_thetas1$emax_k*exp(my_thetas1$theta_rand[,id,7])
  ed50 = my_thetas1$ed50*exp(my_thetas1$theta_rand[,id,8])
  
 
  effect_id = array(dim=c(length(my_thetas1$ed50), length(xs)))
  for(i in 1:length(xs)){
    effect_id[,i]= emax_f(x = xs[i], 
                          logit_max_drug_effect = logit_max_drug_effect,
                          emax_k = emax_k, ed50 = ed50)
  }
  id_true = ID_map$label[id]
  effect_id_list[[id]]=colMeans(effect_id)

  lines(xs, 100*colMeans(effect_id), col='lightgrey')
}
lines(xs, 100*colMeans(effect),lwd=3,col='red')

```
